# This is a basic workflow to help you get started with Actions
name: OWASP ZAP API Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar -xzf ZAP_2.11.0_Linux.tar.gz

      - name: Run ZAP API Scan
        run: |
          cd ZAP_2.11.0
          ./zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true
          
      - name: Generate ZAP Report
        run: |
          ./zap.sh -cmd -lk9hrdmhp1mql9avhem9jj7k12 -api api.report.generate -f report.html -o /zap/report.html
          ./zap.sh -cmd -lk9hrdmhp1mql9avhem9jj7k12 -api api.spider.scan -s Default -r https://hamnaabacus-eval-test.apigee.net/zaptest
          ./zap.sh -cmd -lk9hrdmhp1mql9avhem9jj7k12 -api api.pscan.scan -r ALL -s Default -u https://hamnaabacus-eval-test.apigee.net/zaptest

      - name: Download ZAP Report
        run: |
          mkdir -p report
          cp ZAP_2.11.0/report.html report/

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: report/

